image: node:latest

stages:
  - deploy # Jobs placed in build-stage will run last after test-jobs

deploy:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - apt-get update
    - ssh twoPhase@129.241.96.153 "cd prosjekt \n cd src \n javac *.java \n screen -S server java Tjener"
  only:
    - master
