image: node:latest

stages:
  - deploy # Jobs placed in build-stage will run last after test-jobs

deploy:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - apt-get update
    - apt-get install --assume-yes rsync
    - rsync --archive --delete --exclude='.git' . twoPhase@129.241.96.153:prosjekt
<<<<<<< HEAD
    - ssh twoPhase@129.241.96.153 javac prosjekt/src/*.java && jar cvfm prosjekt/src/tjener.jar prosjekt/src/manifest.txt prosjekt/src/*.class && systemctl --user restart app
=======
    - ssh twoPhase@129.241.96.153 systemctl --user restart app
>>>>>>> 61cc8725e5a4629b4abf8ee89a5971e621b4e411
  only:
    - master
